---
title: 'Accidents'
author: "Seth Buesing"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for data cleaning and plotting
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
library(osmdata)
theme_set(theme_minimal())
```

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r, cache = TRUE}
  accidents_data <- read.csv("C:/Users/coeps/OneDrive/Pictures/Documents/COMP_112/Accidents_Project/local/US_Accidents_Dec21_updated.csv")
```

```{r}
big_streets <- getbb(viewbox = )%>%
  opq(timeout = 100)%>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary", "motorway_link", "primary_link")) %>%
  osmdata_sf()
```


```{r}
  accidents_data_LA <- accidents_data %>% 
    filter((Start_Lng >= -118.9655) & (Start_Lng <= -117.3367) & (Start_Lat >= 33.6818) & (Start_Lat <= 34.4395)) %>%
  select(Start_Lat:End_Lng)

  accidents_data_stpaul <- accidents_data %>% 
    filter(City == "Saint Paul")
```

```{r}
  stpaul_map <- get_stamenmap(
    bbox = c(left = -93.7601 , bottom = 44.6271, right = -92.1313, top = 45.2744), 
    maptype = "terrain",
    zoom = 10)
```  

```{r}
CA_map <- map_data("county", region = "california")
```

```{r}
  LA_map <- get_stamenmap(
     bbox = c(left = -118.9655 , bottom = 33.6818, right = -117.3367, top = 34.4395), 
     maptype = "labels",
     zoom = 9)
```

```{r}
  ggmap(stpaul_map) +
    geom_point(data = accidents_data_stpaul, 
               aes(x = Start_Lng,
                   y = Start_Lat))
```

```{r}
  ggmap(LA_map) +
    geom_point(data = accidents_data_LA, 
               aes(x = Start_Lng,
                   y = Start_Lat),
               size = .2,
               alpha = .1,
               color = "red") +
  geom_sf(data = big_streets$osm_lines,
          inherit.aes = FALSE,
          color = "green",
          size = .1,
          alpha = .9)
  
```

```{r}
  ggplot() +
    geom_map(map = CA_map,
             aes(map_id = subregion))
```


