---
title: 'Final Project'
author: "Jason Whitelaw"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---


```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for data cleaning and plotting
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
library(osmdata)
theme_set(theme_minimal())
```

```{r}
accidents <- read_csv("US_Accidents_Dec21_updated.csv")
```

```{r}
available_tags("highway")
```

```{r}
getbb("Los Angeles USA")
```


```{r}
big_streets <- getbb("Saint Paul USA")%>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("motorway", "primary", "motorway_link", "primary_link")) %>%
  osmdata_sf()
```

```{r}
med_streets <- getbb("Saint Paul USA")%>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("secondary", "tertiary", "secondary_link", "tertiary_link")) %>%
  osmdata_sf()

```

```{r}
small_streets <- getbb("Saint Paul USA")%>%
  opq()%>%
  add_osm_feature(key = "highway", 
                  value = c("residential", "living_street",
                            "unclassified",
                            "service", "footway")) %>%
  osmdata_sf()
```

```{r}
snelling <- big_streets[["osm_lines"]] %>% 
  filter(name=="Snelling Avenue")
```

```{r}
grand <- med_streets[["osm_lines"]] %>% 
  filter(name=="Grand Avenue")
```


```{r}
ggplot() +
   geom_sf(data = med_streets$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = .3,
          alpha = .5) +
  geom_sf(data = small_streets$osm_lines,
          inherit.aes = FALSE,
          color = "#666666",
          size = .2,
          alpha = .3) +
  geom_sf(data = big_streets$osm_lines,
          inherit.aes = FALSE,
          color = "black",
          size = .5,
          alpha = .6) +
  geom_sf(data = snelling,
          inherit.aes = FALSE,
          color = "orange",
          size = 1,
          alpha = 1) +
  geom_sf(data = grand,
          inherit.aes = FALSE,
          color = "red",
          size = 1,
          alpha = 1) +
  theme_void()
```

```{r}
big_streets_la <- getbb("California USA") %>%
  opq(timeout = 100) %>%
  add_osm_feature(key = "highway", 
                  value = c("motorway")) %>%
  osmdata_sf()
```



```{r}
ggplot() +
  geom_sf(data = big_streets_la$osm_lines,
          inherit.aes = FALSE,
          color = "red",
          size = .5,
          alpha = .6)
```

```{r}
census_pop_est_2018 <- read_csv("https://www.dropbox.com/s/6txwv3b4ng7pepe/us_census_2018_state_pop_est.csv?dl=1") %>% 
  separate(state, into = c("dot","state"), extra = "merge") %>% 
  select(-dot) %>% 
  mutate(state = str_to_lower(state))
```


```{r}
accidents %>%
  group_by(State, City) %>%
  summarize(num_accidents = n()) %>%
  arrange(desc(num_accidents))
```

```{r}
accidents %>% 
  filter(is.na(state)==FALSE) %>%
  group_by(state) %>%
  mutate(num_accidents = n()) %>%
  mutate(accidents_per_10000 = (num_accidents/est_pop_2018)*10000) %>%
  select(state, accidents_per_10000) %>%
  unique() %>%
  arrange(desc(accidents_per_10000)) %>% 
  ggplot(aes(x = accidents_per_10000, y = fct_reorder(state, accidents_per_10000))) +
  geom_bar(stat = "identity") +
  labs(y = "", x = "", title = "Total Car Accidents per 10000 Residents, 2016-2021")
```




Relevant Graphs






```{r}
accidents <- read_csv("US_Accidents_Dec21_updated.csv")

states_map <- map_data("state")
```

```{r}
accidents_clean <- accidents %>%
  mutate(state = state.name[match(State, state.abb)]) %>%
  mutate(state = str_to_lower(state)) %>%
  filter(is.na(state)==FALSE) %>%
  mutate(year = substring(Start_Time, 0, 4))
```


```{r}
accidents_anim <- accidents %>%
  group_by(state, year) %>%
  mutate(num_accidents = n()) %>%
  select(state, year, num_accidents) %>%
  unique() %>%
  arrange(year) %>%
  ungroup() %>%
  add_row(year = "2017", state = "north dakota", num_accidents = 0) %>%
  ggplot() +
  geom_map(map = states_map, aes(map_id = state, fill = num_accidents, group = year)) +
  expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map() +
  labs(title = "Number of Car Accidents by State, 2016-2021", subtitle = "Year: {closest_state}", fill = "Number of Accidents") +
  transition_states(year)
```

```{r}
animate(accidents_anim)
```

```{r}
accidents_ca <- accidents_clean %>%
  filter(State == "CA")
```

```{r}
accidents_ca %>%
  filter(is.na(Sunrise_Sunset)==FALSE) %>%
  group_by(year) %>%
  mutate(num_accidents = n()) %>%
  ungroup() %>%
  group_by(year, Sunrise_Sunset) %>%
  mutate(percent_day_night = n()/num_accidents) %>%
  ungroup() %>%
  select(percent_day_night, year, Sunrise_Sunset) %>%
  unique() %>%
  ggplot() +
  geom_col(aes(x = year, y = percent_day_night, fill = Sunrise_Sunset)) +
  labs(title = "Percent of Day/Night Accidents in California by Year", fill = "Time of Day") +
  ylab("")
```

```{r}
accidents_ca %>%
  filter(is.na(Weather_Condition)==FALSE) %>%
  group_by(year) %>%
  mutate(num_accidents = n()) %>%
  ungroup() %>%
  group_by(year, Weather_Condition) %>%
  mutate(percent_weather = n()/num_accidents) %>%
  filter(percent_weather>.01) %>%
  ungroup() %>%
  select(percent_weather, year, Weather_Condition) %>%
  unique() %>%
  group_by(year) %>%
  mutate(other = 1-sum(percent_weather)) %>%
  ungroup() %>%
  add_row(year = "2016", Weather_Condition = "Other", percent_weather = 0.02103897) %>%
  add_row(year = "2017", Weather_Condition = "Other", percent_weather = 0.02290385) %>%
  add_row(year = "2018", Weather_Condition = "Other", percent_weather = 0.02343750) %>%
  add_row(year = "2019", Weather_Condition = "Other", percent_weather = 0.03828895) %>%
  add_row(year = "2020", Weather_Condition = "Other", percent_weather = 0.03021382) %>%
  add_row(year = "2021", Weather_Condition = "Other", percent_weather = 0.03736665) %>%
  ggplot() +
  geom_col(aes(x = "", y = percent_weather, fill = Weather_Condition)) +
  coord_polar("y", start = 0) +
  facet_wrap(vars(year)) +
  labs(title = "Types of Weather During Accidents in California by Year", fill = "Weather") +
  theme_void()
```








