---
title: 'Final Project'
author: "Kai Yamanishi"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---


```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```

```{r libraries}
library(tidyverse)     # for data cleaning and plotting
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
library(scales)        # for changing graph scales
theme_set(theme_minimal())
```

```{r}
accidents <- read_csv("US_Accidents_Dec21_updated.csv") %>% 
  mutate(state = state.name[match(State, state.abb)]) %>%
  mutate(state = str_to_lower(state))

census_pop_est_2018 <- read_csv("https://www.dropbox.com/s/6txwv3b4ng7pepe/us_census_2018_state_pop_est.csv?dl=1") %>%
  separate(state, into = c("dot","state"), extra = "merge") %>% 
  select(-dot) %>% 
  mutate(state = str_to_lower(state))
```

```{r}
census_accidents <- left_join(accidents, census_pop_est_2018)
```


```{r, fig.width=10, fig.height=8, fig.alt="Total car accidents in each US state between 2016 and 2021."}
census_accidents %>% 
  group_by(state) %>% 
  summarise(total_accidents_adjusted = n()/mean(est_pop_2018)) %>% 
  ungroup() %>% 
  ggplot(aes(y = fct_reorder(state, total_accidents_adjusted), x = total_accidents_adjusted)) +
  geom_bar(stat = "identity") +
  labs(y = "", x = "", title = "Total Car Accidents 2016-2021")
```
